# Generated by Django 4.1.2 on 2022-10-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='owner',
        ),
    ]
