# Generated by Django 4.1.2 on 2022-10-17 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_comment_deleted_at_alter_like_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='post.post'),
            preserve_default=False,
        ),
    ]
