# Generated by Django 4.1.2 on 2022-10-17 14:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0007_like_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='like',
            new_name='PostLike',
        ),
    ]
