# Generated by Django 4.1.2 on 2022-12-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
